apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Svcname }}
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Values.Appname }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.Appname }}
